eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
server:
  port: 8888
zuul:
  routes:
    service-a:
      path: /service/**
      serviceId: consumer-feign
#      strip-prefix: false
#\u8BBF\u95EE\u8DEF\u5F84http://localhost:8888/service/hi?name=xwj
  ignored-services:
    - producer
#zuul\u9ED8\u8BA4\u628A\u6240\u4EE5\u670D\u52A1\u4EE5serviceId:path/serviceId/\u8DEF\u5F84\u6620\u5C04\uFF0C\u4E0D\u5B89\u5168
spring:
  application:
    name: zuul-demo
#ribbon:
#  ConnectTimeout: 250 # \u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4(ms)
#  ReadTimeout: 2000 # \u901A\u4FE1\u8D85\u65F6\u65F6\u95F4(ms)
#  OkToRetryOnAllOperations: true # \u662F\u5426\u5BF9\u6240\u6709\u64CD\u4F5C\u91CD\u8BD5
#  MaxAutoRetriesNextServer: 2 # \u540C\u4E00\u670D\u52A1\u4E0D\u540C\u5B9E\u4F8B\u7684\u91CD\u8BD5\u6B21\u6570
#  MaxAutoRetries: 1 # \u540C\u4E00\u5B9E\u4F8B\u7684\u91CD\u8BD5\u6B21\u6570
#hystrix:
#  command:
#  	default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMillisecond: 6000 # \u7194\u65AD\u8D85\u65F6\u65F6\u957F\uFF1A6000ms