eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
server:
  port: 8888
zuul:
  routes:
#    service-a:  # 路由名称，随意
#      path: /service/**     #匹配前缀，此时访问路径为http://localhost:8888/service/hi?name=xwj
#      serviceId: consumer-feign
    consumer-feign: /service/**   #上面三行的简便写法(zuul会把所有微服务都默认配置该路由consumer-feign: /consumer-feign/**)
#      strip-prefix: false  #不去除前缀：/service/**直接转发到consumer-feign
  ignored-services:
    - producer   #zuul禁止访问serviceId： http://localhost:8888/producer/hi?name=xwj
spring:
  application:
    name: zuul-demo
#ribbon:
#  ConnectTimeout: 250 # 连接超时时间(ms)
#  ReadTimeout: 2000 # 通信超时时间(ms)
#  OkToRetryOnAllOperations: true # 是否对所有操作重试
#  MaxAutoRetriesNextServer: 2 # 同一服务不同实例的重试次数
#  MaxAutoRetries: 1 # 同一实例的重试次数
#hystrix:
#  command:
#  	default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMillisecond: 6000 # 熔断超时时长6000ms