eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/,http://localhost:8002/eureka/
server:
  port: 8202
spring:
  application:
    name: consumer-feign
feign:
  hystrix:
    enabled: true