eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/,http://localhost:8002/eureka/
  instance:
      prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
      ip-address: 127.0.0.1 # 指定自己的ip信息，当存在docker或多网卡时，ip可能混乱
server:
  port: 8202
spring:
  application:
    name: consumer-feign
feign:
  hystrix:
    enabled: true